### PR TITLE
 Update 2.1.1

### PR DESCRIPTION
**Pull request by Thanos420NoScope**

### CODE REVIEW

**Comment by fosskers** [comment]
Do you have merge power for this repo?

**Comment by Thanos420NoScope** [comment]
I do not currently. Used a work account before when we made the script. I made a personal one since.

**Comment by fosskers** [comment]
Is this good to merge?

**Comment by Thanos420NoScope** [comment]
Yes, it changes the links to the new updated node version, and changes the update links in the readme.

**Pull request merged**
